---
- name: Ensure homebrew is installed.
  git:
    repo: https://github.com/Homebrew/brew.git
    version: master
    dest: "{{ homebrew_install_path }}"
    update: yes
    accept_hostkey: true

- name: Check if homebrew binary is already in place.
  stat: path=/usr/local/bin/brew
  register: homebrew_binary

- name: Get list of tapped homebrew taps.
  command: brew tap
  register: homebrew_tap_list
  changed_when: false

- name: Tap configured homebrew taps.
  command: "brew tap {{ item }}"
  when: "item not in homebrew_tap_list.stdout"
  with_items: "{{homebrew_taps}}"

- name: Get list of installed homebrew packages.
  command: brew list --formula
  register: homebrew_list
  changed_when: false

- name: Install configured homebrew packages.
  command: "brew install {{ item }} {{homebrew_args[item] | default('')}}"
  with_items: "{{homebrew_installed_packages}}"
  when: "item not in homebrew_list.stdout"

