---
rbenv: 
  env: user
  version: v0.4.0
  ruby_version: 2.1.2
homebrew_installed_packages:
  - ack
  - ant
  - antiword
  - aspell
  - atk
  - autobench
  - autoconf
  - automake
  - autossh
  - bash-completion
  - bcrypt
  - beanstalk
  - boost
  - bwm-ng
  - cairo
  - cloc
  - cloog
  - cmake
  - coreutils
  - cscope
  - ctags
  - dialog
  - direnv
  - e2fsprogs
  - ec2-api-tools
  - elasticsearch
  - erlang
  - etcd
  - faac
  - fasd
  - fdk-aac
  - ffmpeg
  - findutils
  - flac
  - fleetctl
  - fontconfig
  - freetype
  - frei0r
  - fribidi
  - gcc
  - gdbm
  - gdk-pixbuf
  - geoip
  - gettext
  - giflib
  - gist
  - git
  - git-extras
  - git-flow
  - glib
  - gmp
  - gnu-getopt
  - gnu-sed
  - gnupg
  - gnupg2
  - gnutls
  - go
  - goaccess
  - gobject-introspection
  - graphicsmagick
  - grc
  - gsl
  - gtk+
  - harfbuzz
  - htop-osx
  - httperf
  - httpie
  - hub
  - icu4c
  - id3tool
  - imagemagick 
  - ios-webkit-debug-proxy
  - irssi
  - isl
  - jasper
  - jpeg
  - jsonpp
  - juju
  - lame
  - languagetool
  - legit
  - leiningen
  - lesspipe
  - lftp
  - libass
  - libassuan
  - libev
  - libevent
  - libffi
  - libgcrypt
  - libgpg-error
  - libimobiledevice
  - libksba
  - libmagic
  - libmpc
  - libogg
  - libplist
  - libpng
  - libsamplerate
  - libsndfile
  - libsodium
  - libssh2
  - libtasn1
  - libtiff
  - libtool
  - libusb
  - libusb-compat
  - libvo-aacenc
  - libvorbis
  - libvpx
  - libxml2
  - libxslt
  - libyaml
  - links
  - little-cms
  - little-cms2
  - llvm
  - lua
  - lynx
  - man2html
  - maven
  - md5sha1sum
  - mercurial
  - midnight-commander
  - mitmproxy
  - mobile-shell
  - mogenerator
  - mongodb
  - monit
  - mpfr
  - mpssh
  - mtr
  - multimarkdown
  - mutt
  - mysql
  - neo4j
  - neon
  - netcat
  - nethack
  - nettle
  - nginx
  - ninja
  - nmap
  - node
  - oniguruma
  - opencore-amr
  - openjpeg
  - openssl
  - opus
  - orc
  - ossp-uuid
  - pandoc
  - pango
  - parallel
  - pass
  - pcre
  - pidof
  - pinentry
  - pixman
  - pkg-config
  - plenv
  - poppler
  - postgresql
  - protobuf
  - pssh
  - pstree
  - pth
  - pwgen
  - python
  - python3
  - rainbarf
  - ragel
  - rbenv
  - readline
  - reattach-to-user-namespace
  - redis
  - riak
  - rlwrap
  - rtmpdump
  - rust
  - s-lang
  - s3cmd
  - sbt
  - schroedinger
  - scons
  - sdl
  - siege
  - sl
  - sloccount
  - smartmontools
  - speex
  - sphinx
  - sqlite
  - sshuttle
  - subversion
  - swftools
  - swig
  - tbb
  - tcpflow
  - tcptrace
  - texi2html
  - texinfo
  - the_silver_searcher
  - theora
  - tmux
  - tomcat
  - tree
  - ttfautohint
  - unixodbc
  - unrar
  - usbmuxd
  - v
  - v8
  - varnish
  - vifm
  - neovim
  - watch
  - webkit2png
  - webp
  - weechat
  - wemux
  - wget
  - wrk
  - wxmac
  - x264
  - xapian
  - xvid
  - xz
  - yasm
  - youtube-dl
  - yuicompressor
  - z
  - zeromq
  - zsh-lovers
homebrew_args:

homebrew_taps:
    - homebrew/cask
    - homebrew/cask-fonts
    - adoptopenjdk/openjdk
homebrew_cask_packages_packages:
  - xquartz
  - alfred
  - amethyst
  - betterzipql
  - bittorrent-sync
  - calibre
  - colorpicker-hex
  - dash
  - dropbox
  - firefox
  - gitx
  - google-chrome
  - inkscape
  - iterm2
  - java
  - karabiner
  - osxfuse
  - plex-media-server
  - qlcolorcode
  - qlmarkdown
  - qlstephen
  - quicklook-csv
  - quicklook-json
  - skitch
  - techstoreclub-simple-comic
  - slate
  - steam
  - the-unarchiver
  - totalspaces
  - transmission
  - tuntap
  - vagrant
  - vlc

installed_debs:
  - zsh
  - cmake
  - python-dev
  - tmux
  - vim
