---
- include_tasks: debianish.yml
  when: ansible_pkg_mgr == 'apt'
- include_tasks: archish.yml
  when: ansible_pkg_mgr == 'pacman'
- include_tasks: redhatish.yml
  when: ansible_pkg_mgr == 'yum'
- include_tasks: osx.yml
  when: ansible_os_family == 'Darwin'

- name: Setup dev scripts
  shell: bash ~/.dotfiles/init/{{ item | basename }}
  with_fileglob:
    - init/*

- name: remove existing files.
  stat: path="~/.{{ item|basename }}"
  register: result
  with_lines: ls ~/.dotfiles/link


- shell: "mkdir -p ~/.dotfiles/backups/{{ ansible_date_time.date}} && mv ~/.{{ item.item|basename }} ~/.dotfiles/backups/{{ ansible_date_time.date }}/"
  when: "item.stat.islnk is defined and item.stat.islnk==false"
  with_items: "{{result.results}}"

- name: Copy files
  copy: src=~/.dotfiles/link/{{ item|basename }} dest=~/.{{ item|basename }} force=yes
  with_lines: ls ~/.dotfiles/copy

- name: Link files
  file: src=~/.dotfiles/link/{{ item|basename }} path=~/.{{ item|basename }} state=link force=yes
  with_lines: ls ~/.dotfiles/link

- name: Set correct mode for ssh keys
  file: path={{item}} mode=0700
  with_items:
    - ~/.dotfiles/link/ssh
    - ~/.dotfiles/link
    - ~/.dotfiles
