---
- file:  src=~/.dotfiles/link/{{ item|basename }} path=~/.{{ item|basename }} state=link force=yes
  with_anyglob: 
    - link/*
- copy:  src=~/.dotfiles/link/{{ item|basename }} dest=~/.{{ item|basename }} force=yes
  with_anyglob: 
    - copy/*
- shell: bash ~/.dotfiles/init/{{ item | basename }}
  with_fileglob:
    - init/*
    
