if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
if [ -e /Users/marcus/.nix-profile/etc/profile.d/nix.sh ]; then . /Users/marcus/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
