# Add binaries into the path
PATH=~/.dotfiles/bin:$PATH
export PATH
set -o vi

# Source all files in ~/.dotfiles/source/
function src() {
  local file
  if [[ "$1" ]]; then
    source "$HOME/.dotfiles/source/$1.sh"
  else
    for file in ~/.dotfiles/source/*; do
      source "$file"
    done
  fi
}

# Run dotfiles script, then source.
function dotfiles() {
  ~/.dotfiles/bin/dotfiles "$@" && src
}

#src

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting
alias vi="vim -u ~/.vimrc.mini"
export PS1="\\u@\h \\W]\\$"
alias fuck='sudo $(fc -ln -1)'
export PYTHONPATH=/usr/local/lib/python2.7/site-packages:$PYTHONPATH

#THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
export SDKMAN_DIR="/home/marcus/.sdkman"
[[ -s "/home/marcus/.sdkman/bin/sdkman-init.sh" ]] && source "/home/marcus/.sdkman/bin/sdkman-init.sh"
#export PATH="$HOME/rakudo/install/bin:$HOME/install/share/perl6/site/bin:$PATH"
alias update-perl6='
    cd ~/rakudo;
    git pull;
    perl Configure.pl --gen-moar --gen-nqp --backends=moar;
    make;
    make test;
    make install'
export FLAGS_GETOPT_CMD="$(brew --prefix gnu-getopt)/bin/getopt"
export FLAGS_GETOPT_CMD="$(brew --prefix gnu-getopt)/bin/getopt"
