set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'elzr/vim-json'
Bundle 'airblade/vim-gitgutter'
"Bundle 'othree/eregex.vim'
Bundle 'lepht/perlomni.vim'
Bundle 'fatih/vim-go'
Bundle 'joshdick/onedark.vim'
Bundle 'benmills/vimux'
Bundle 'bling/vim-airline'
Bundle 'pearofducks/ansible-vim'
Bundle 'christoomey/vim-tmux-navigator'
Bundle 'csexton/jekyll.vim'
"Bundle 'edkolev/tmuxline.vim'
Bundle 'glench/Vim-Jinja2-Syntax'
Bundle 'gmarik/vundle'
Bundle 'godlygeek/tabular'
Bundle 'honza/vim-snippets'
Bundle 'jazzCore/ctrlp-cmatcher'
Bundle 'ctrlpvim/ctrlp.vim'
Bundle 'majutsushi/tagbar'
Bundle 'MarcWeber/vim-addon-mw-utils'
Bundle 'mattn/gist-vim'
Bundle 'mattn/webapi-vim'
Bundle 'ngmy/vim-rubocop'
Bundle 'othree/html5.vim'
Bundle 'klen/python-mode'
Bundle 'pangloss/vim-javascript'
Bundle 'rizzatti/dash.vim'
Bundle 'rizzatti/funcoo.vim'
Bundle 'mileszs/ack.vim'
Bundle 'scrooloose/syntastic'
Bundle 'sirVer/ultisnips'
Bundle 'spllr/vim-padrino'
Bundle 'terryma/vim-multiple-cursors'
Bundle 'tomtom/tlib_vim'
Bundle 'tomtom/vimtlib'
Bundle 'tonchis/vim-to-github'
Bundle 'tpope/vim-dispatch'
Bundle 'tpope/vim-endwise'
Bundle 'lambdalisue/vim-gita'
Bundle 'tpope/vim-rake'
Bundle 'tpope/vim-sensible'
Bundle 'tpope/vim-markdown'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-repeat'
Bundle 'tpope/vim-speeddating'
Bundle 'tpope/vim-commentary'
"Bundle 'Valloric/YouCompleteMe'
Bundle 'Shougo/neocomplete.vim'
Bundle 'vim-pandoc/vim-pandoc'
Bundle 'hokaccha/vim-prove'
Bundle 'vim-pandoc/vim-pandoc-syntax' 
Bundle 'vim-perl/vim-perl'
Bundle 'vim-ruby/vim-ruby'
Bundle 'yko/mojo.vim' 
Bundle 'mivok/vimtodo'
Bundle 'zah/nimrod.vim'
Bundle 'bronson/vim-trailing-whitespace'
Bundle 'janko-m/vim-test'

colorscheme onedark
 
filetype plugin indent on
 
syntax on
set number
set mouse=
set mousehide

set hlsearch
set showmatch
set incsearch
set ignorecase
set autoindent
set history=1000
set cursorline
set expandtab
set shiftwidth=2
set tabstop=2
set softtabstop=2
set clipboard=unnamed
set directory=/tmp
set pastetoggle=<leader>v

set statusline=%<\ %n:%f\ %m%r%y%=%-35.(line:\ %l\ of\ %L,\ col:\ %c%V\ (%P)%)

" Airline
let g:airline#extensions#tabline#enabled = 0
let g:airline_powerline_fonts = 1
set background=dark
let g:airline_theme = 'onedark'

let g:tagbar_left = 1
let g:tagbar_sort = 0
let g:tagbar_autoshowtag = 1
let g:tagbar_autoclose = 1
let g:tagbar_ctags_bin = '/usr/local/bin/ctags'
let g:tagbar_width = 30 
let g:tagbar_foldlevel = 2

let g:vim_markdown_folding_disabled=1
let g:pymode_folding = 0

let g:jekyll_path = "~/Source/blog"
let g:syntastic_javascript_checkers = ['jsxhint']
let g:pandoc#modules#disabled = ["folding"]
"let g:pandoc#formatting#mode = 'ha'
let g:pandoc#formatting#textwidth = 79


autocmd FileType ruby,eruby let g:rubycomplete_buffer_loading = 1 
autocmd FileType ruby,eruby let g:rubycomplete_classes_in_global = 1
autocmd FileType ruby,eruby let g:rubycomplete_rails = 1
autocmd BufNewFile,BufReadPost *.go set filetype=go
autocmd FileType go compiler go
autocmd FileType go autocmd BufWritePre <buffer> GoFmt
autocmd BufNewFile,BufRead *.tt setf tt2
au BufRead,BufNewFile *.md,*.markdown setlocal textwidth=79 wrap linebreak nolist




if has("autocmd")
  au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal g'\"" | endif
endif 


:nmap <leader>a :Ack 
:nmap <silent> <leader>d <Plug>DashGlobalSearch
:nmap <silent> <leader>p :TagbarToggle<cr>
:nmap <silent> <leader>n :cnext<cr>
nnore <esc><esc> :let @/ = ""<cr>

:nmap <silent> <leader>; :CtrlP<cr>
:nmap ; :CtrlPBuffer<cr>
let g:ctrlp_match_window = 'top,order:ttb,min:1,max:10,results:10'
let g:ctrlp_switch_buffer = 0
"let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']
let g:ctrlp_working_path_mode = 2
let g:ctrlp_cmd = 'CtrlPMRUFile'


if $TERM_PROGRAM =~ "iTerm"
  if exists('$TMUX')
    let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
    let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
  else
    let &t_SI = "\<Esc>]50;CursorShape=1\x7"
    let &t_EI = "\<Esc>]50;CursorShape=0\x7"
  endif
endif
noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

let g:UltiSnipsExpandTrigger ="<Leader><Tab>"
let g:UltiSnipsJumpForwardTrigger="<Leader><Tab>"
let g:UltiSnipsJumpBackwardTrigger="<Leader><s-Tab>"

" Tab navigation
let g:lasttab = 1
nnoremap tt :exe "tabn ".g:lasttab<CR>
au TabLeave * let g:lasttab = tabpagenr()
nnoremap tn :tabnew<CR>
nnoremap tj  :tabfirst<CR>
nnoremap tl  :tabnext<CR>
nnoremap th  :tabprev<CR>
nnoremap tk  :tablast<CR>
nnoremap te  :tabedit<space>
nnoremap tm  :tabm<Space>
nnoremap td  :tabclose<CR>
map <space> viw


command! Fuck w !sudo tee % >/dev/null

noremap <C-_> :call AckSearch()<CR>
 
function! AckSearch()
  let a:top_level = split(expand("%"), "/")
  let a:query = getline("'<")
  let a:start = getpos("'<")[2]
  let a:stop = getpos("'>")[2]
 
  if a:start == a:stop
    let a:query = expand("<cword>")
  else
    let a:query = a:query[a:start - 1: a:stop - 1]
  endif
 
  call ack#Ack("grep!", a:query . " " . a:top_level[0])
endfunction

if executable('ag')
    let g:ackprg = 'ag --vimgrep'
endif

let g:ansible_extra_syntaxes = "sh.vim perl.vim"

:autocmd BufRead,BufNewFile /home/marcus/Source/_rg/* call SetRgOptions()

function SetRgOptions()
  let g:syntastic_enable_perl_checker = 1
  setlocal tabstop=4 shiftwidth=4
  let g:syntastic_perl_lib_path = [ "./lib", "./lib/auto", "/home/marcus/Source/_rg/libraries/lib" ]
  let g:syntastic_perl_args_after = '--quiet --nocolor --verbose "\%s:\%f:\%l:\%c:(\%s) \%m (\%e)\n" -p ~/Source/_rg/libraries/.perlcriticrc'
  let g:syntastic_perl_checkers = ['perl','perlcritic']
endfunction

command -range=% -nargs=* Tidy <line1>,<line2>!
  \perltidy <args>

"Use 24-bit (true-color) mode in Vim/Neovim when outside tmux.
"If you're using tmux version 2.2 or later, you can remove the outermost $TMUX check and use tmux's 24-bit color support
"(see < http://sunaku.github.io/tmux-24bit-color.html#usage > for more information.)
if (empty($TMUX))
  if (has("nvim"))
    "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
    let $NVIM_TUI_ENABLE_TRUE_COLOR=1
  endif
  "For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
  "Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
  " < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
  if (has("termguicolors"))
    set termguicolors
  endif
endif


" OS X-like space bar to scroll.
nnoremap <Space> <C-F>


nmap <silent> <leader>t :TestNearest<CR>
nmap <silent> <leader>T :TestFile<CR>
nmap <silent> <leader>A :TestSuite<CR>
nmap <silent> <leader>l :TestLast<CR>
nmap <silent> <leader>g :TestVisit<CR>

let test#strategy="neovim"

set magic
let g:acp_enableAtStartup = 0
" Use neocomplete.
let g:neocomplete#enable_at_startup = 1
" " Use smartcase.
let g:neocomplete#enable_smart_case = 1

inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
noremap <expr><C-h> neocomplete#smart_close_popup()."\<C-h>"
inoremap <expr><BS> neocomplete#smart_close_popup()."\<C-h>"
"inoremap <expr><Space> pumvisible() ? "\<C-y>" : "\<Space>"

