# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.

[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return


if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi


#
# User configuration sourced by interactive shells
#
export ZPLUG_HOME=$HOME/.dotfiles/libs/zplug


# Set to this to use case-sensitive completion
CASE_SENSITIVE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

DISABLE_UPDATE_PROMPT="true"

KEYTIMEOUT=1

setopt inc_append_history
setopt share_history
export HISTFILE=~/.zsh_history
export HISTSIZE=100000
export SAVEHIST=100000


# ssh agent config

bindkey -v
bindkey -M vicmd "/" history-incremental-search-backward
bindkey '^R' history-incremental-search-backward
bindkey '^R' history-incremental-pattern-search-backward
bindkey '^?' backward-delete-char
bindkey '^h' backward-delete-char
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward
bindkey '^k' kill-line
bindkey -a u undo
bindkey -a '^R' redo
bindkey '^G' what-cursor-position

autoload -U up-line-or-beginning-search
autoload -U down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search
bindkey  "^[[A" up-line-or-beginning-search # Up
bindkey  "^[[B" down-line-or-beginning-search # Down

# Source all files in ~/.dotfiles/source/
function src() {
  local file
  if (( $# == 0 )); then for file in ~/.dotfiles/source/*; do
      source "$file"
    done
  else
    source "$HOME/.dotfiles/source/$1.sh"
  fi
}

# Run dotfiles script, then source.
function dotfiles() {
  ~/.dotfiles/bin/dotfiles "$@" && src
}

src

if [ "$TERM_PROGRAM" = "iTerm" ]; then
  test -e ${HOME}/.iterm2_shell_integration.zsh && source ${HOME}/.iterm2_shell_integration.zsh
fi

if [ "$0" = "/usr/sbin/lightdm-session" -a "$DESKTOP_SESSION" = "i3" ]; then
    export $(gnome-keyring-daemon -s)
fi


# And kubectl command completion.
source <(kubectl completion zsh)

[[ -x /usr/bin/fortune && -x /usr/bin/cowsay ]] && fortune /usr/share/fortune/vimtips | cowsay -f moose

[[ -f /usr/share/autoenv/activate.sh ]] && source /usr/share/autoenv/activate.sh

export GITHUB_USERNAME=marcusramberg
export JSONNET_PATH=~/Source/DNB/grafana-jsonnet-config/grafonnet-lib
# start in normal mode
#

[[ -f ~/.nix-profile/etc/profile.d/nix.sh ]] && . ~/.nix-profile/etc/profile.d/nix.sh

autoload -U zmv
alias mmv="noglob zmv -W"
export TABLE_TERM_SIZE=150

autoload -U +X bashcompinit && bashcompinit

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
# fzf
export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
    --color=fg:#e5e9f0,bg:#3b4251,hl:#81a1c1
    --color=fg+:#e5e9f0,bg+:#3b4251,hl+:#81a1c1
    --color=info:#eacb8a,prompt:#bf6069,pointer:#b48dac
    --color=marker:#a3be8b,spinner:#b48dac,header:#a3be8b'
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND='rg --files --hidden'


source "${ZPLUG_HOME}/init.zsh"
zplug bobsoppe/zsh-ssh-agent
zplug mafredri/zsh-async
zplug "romkatv/powerlevel10k", use:powerlevel10k.zsh-theme
zplug "zsh-users/zsh-autosuggestions", defer:3
zplug "zsh-users/zsh-syntax-highlighting", defer:2
#zplug "marlonrichert/zsh-autocomplete"
zplug "b4b4r07/zsh-vimode-visual", defer:3
zplug "rupa/z", use:z.sh
zplug "zsh-users/zsh-completions"
zplug load

zstyle ':autocomplete:tab:*' completion insert
zstyle ':autocomplete:list-choices:*' min-input 3

export JAVA_HOME=/Users/marcus/.jenv/versions/11.0
complete -o nospace -C /usr/local/bin/terraform terraform

export LC_ALL=en_US.UTF-8
