-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = { "go" },
--   callback = function()
--     vim.lsb.buf.formatting()
--   end,
-- })
-- vim.api.nvim_create_autocmd("FileType", {
--   pattern = { "lua" },
--   callback = function()
--     vim.lsp.buf.formatting_sync(nil, 100)
--   end,
-- })
